[package]
name = "quantacipher-python"
version = "0.2.0"
edition = "2021"
description = "Zero-trust PQC (Kyber) encryption Python bindings"
repository = "https://github.com/xaexaex/quantacipher"
license = "MIT"
readme = "README.md"
authors = ["QuantaLabs"]

[lib]
name = "_quantacipher_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
quantacipher-core = { path = "../quantacipher-core" }
