[package]
name = "quantacipher-python"
version = "0.1.0"
edition = "2021"
description = "Zero-trust PQC (Kyber) encryption Python bindings"
repository = "https://github.com/xaexaex/quantacipher"
license = "UNLICENSED"
authors = ["QuantaLabs"]

[lib]
name = "quantacipher"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
quantacipher-core = { path = "../quantacipher-core" }
