steps:
  # Step 1: Build the container image using the Gateway Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quantacipher:$COMMIT_SHA'
      - '-f'
      - 'quantacipher-gateway/Dockerfile'
      - 'quantacipher-gateway'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quantacipher:$COMMIT_SHA'

  # Step 3: Deploy the image to the Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quantacipher'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quantacipher:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4000'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quantacipher:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
