/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const encrypt_local_kyber: (a: number, b: number) => [number, number];
export const generate_keypair: () => [number, number];
export const get_wasm_version: () => [number, number];
export const secure_decrypt: (a: number, b: number, c: number, d: number) => [number, number];
export const secure_encrypt: (a: number, b: number, c: number, d: number) => [number, number];
export const vault_encrypt: (a: number, b: number) => [number, number];
export const __wbg_get_params_ciphertextBytes: (a: number) => number;
export const __wbg_get_params_publicKeyBytes: (a: number) => number;
export const __wbg_get_params_secretKeyBytes: (a: number) => number;
export const __wbg_get_params_sharedSecretBytes: (a: number) => number;
export const __wbg_kex_free: (a: number, b: number) => void;
export const __wbg_keys_free: (a: number, b: number) => void;
export const __wbg_params_free: (a: number, b: number) => void;
export const decapsulate: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const encapsulate: (a: number, b: number) => [number, number, number];
export const kex_ciphertext: (a: number) => [number, number];
export const kex_new: (a: number, b: number) => number;
export const kex_set_ciphertext: (a: number, b: number, c: number) => void;
export const kex_set_sharedSecret: (a: number, b: number, c: number) => void;
export const kex_sharedSecret: (a: number) => [number, number];
export const keypair: () => [number, number, number];
export const keys_pubkey: (a: number) => [number, number];
export const keys_secret: (a: number) => [number, number];
export const params_ciphertextBytes: () => number;
export const params_publicKeyBytes: () => number;
export const params_secretKeyBytes: () => number;
export const params_sharedSecretBytes: () => number;
export const keys_new: () => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
