const fs = require('fs');
const path = require('path');

const pkgDir = path.join(__dirname, 'pkg');
const wasmFile = path.join(pkgDir, 'quantacipher_wasm_bg.wasm');
const jsFile = path.join(pkgDir, 'quantacipher_wasm.js');
const pkgJsonFile = path.join(pkgDir, 'package.json');

if (!fs.existsSync(wasmFile)) {
    console.log("WASM file not found, skipping base64 injection.");
    process.exit(0);
}

// 1. Read wasm as base64
const wasmBuffer = fs.readFileSync(wasmFile);
const wasmBase64 = wasmBuffer.toString('base64');

// 2. Read js and replace
let jsContent = fs.readFileSync(jsFile, 'utf8');

// Match the specific lines generated by wasm-pack --target nodejs
const searchString = "const wasmPath = `${__dirname}/quantacipher_wasm_bg.wasm`;\nconst wasmBytes = require('fs').readFileSync(wasmPath);";
const replaceString = `const wasmBytes = Buffer.from('${wasmBase64}', 'base64');`;

if (jsContent.includes("require('fs')")) {
    // We replace the exact string or fallback to regex
    if (jsContent.includes(searchString)) {
        jsContent = jsContent.replace(searchString, replaceString);
    } else {
        const fallbackSearch = /const wasmPath = [^\n]+;\s*const wasmBytes = require\('fs'\)\.readFileSync\(wasmPath\);/g;
        jsContent = jsContent.replace(fallbackSearch, replaceString);
    }
    
    fs.writeFileSync(jsFile, jsContent);
    console.log("Successfully embedded WASM as Base64 in JavaScript!");
} else {
    console.log("JS file does not contain fs.readFileSync, skipping.");
}

// 3. Remove wasm file
try {
    fs.unlinkSync(wasmFile);
} catch (e) {
    console.log("Failed to delete wasm file: " + e.message);
}

// 4. Update package.json to remove wasm file from "files" array
let pkgJson = JSON.parse(fs.readFileSync(pkgJsonFile, 'utf8'));
if (pkgJson.files) {
    pkgJson.files = pkgJson.files.filter(f => !f.endsWith('.wasm'));
    fs.writeFileSync(pkgJsonFile, JSON.stringify(pkgJson, null, 2));
}

console.log("Done.");
