[package]
name = "quantacipher-wasm"
version = "0.1.0"
edition = "2021"
description = "Zero-trust PQC (Kyber) encryption WASM bindings"
repository = "https://github.com/xaexaex/quantacipher"
license = "UNLICENSED"
authors = ["QuantaLabs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
quantacipher-core = { path = "../quantacipher-core" }
getrandom = { version = "0.2", features = ["js"] }
